### ISSUE TITLE
EACCES: permission denied when installing on Debian

### ISSUE THREAD

**Issue by mannouman** [hcnode/tumblr-get#2]
Hi, 

I have an error when installing on debian Jessie (installation as root, bower is installed)

Error: EACCES: permission denied, open '/root/.config/configstore/bower-github.json'
You don't have access to this file.

Any idea ? 

Thanks

**Comment by hcnode** [comment]
Hi, thanks for your issue report, I have not tried on debian Jessie(maybe this issue caused related to bower, I am not sure), but I have update jquery dependence from bower to npm, so no need bower any more, just try again!

**Comment by mannouman** [comment]
Hi !

Thanks a lot for your reply ! I will try asap today and let you know...

Thanks again for your help

**Comment by mannouman** [comment]
Great ! It works fine now

You can close this issue, thanks ;-)
